version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=jobs_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init/sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
